name: Test
on: [push, pull_request]
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install --no-install-recommends --assume-yes libglfw3-dev
      - name: Run "cargo build"
        run: cargo build
      - name: Run "cargo test"
        run: cargo test
